<div class="form-group">

<label for="rotulo">Escríbe el color:</label>&nbsp;
	<label for="usr">
		<input type="text" id="myInputRAL" class="" placeholder="Ejemplo: RAL 1000" title="Escriba el nombre o indicio del color" style="height: 50px;padding: 3% 0;
  border-radius: 14px;
  border: 3px #ffffff solid;">  
	</label>

</div>

<br/>

<div id="listRAL">


<div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1000" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(190, 189, 127)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1000</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(194, 176, 120)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(198, 166, 100)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(229, 190, 1)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(205, 164, 52)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(169, 131, 7)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1006" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(228, 160, 16)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1006</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(220, 157, 0)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(138, 102, 66)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(199, 180, 70)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1013" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(238, 234, 205)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1013</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1014" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(225, 204, 79)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1014</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1015" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(230, 214, 144)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1015</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1016" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(237, 255, 33)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1016</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1017" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(245, 208, 51)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1017</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1018" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(248, 243, 43)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1018</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1019" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(158, 151, 100)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1019</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1020" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(153, 153, 80)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1020</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1021" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(243, 218, 11)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1021</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1023" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(250, 210, 1)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1023</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1024" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(174, 160, 75)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1024</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1026" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(255, 255, 0)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1026</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1027" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(157, 145, 1)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1027</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1028" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(244, 169, 0)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1028</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1032" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(214, 174, 1)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1032</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1033" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(243, 165, 5)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1033</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1034" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(239, 169, 74)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1034</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1035" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(106, 93, 77)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1035</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1036" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(112, 83, 53)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1036</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 1037" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(243, 159, 24)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 1037</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2000" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(237, 118, 14)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2000</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(201, 60, 32)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(203, 40, 33)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(255, 117, 20)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(244, 70, 17)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(255, 35, 1)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(255, 164, 32)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2008" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(247, 94, 37)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2008</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2009" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(245, 64, 33)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2009</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2010" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(216, 75, 32)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2010</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(236, 124, 38)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(229, 81, 55)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 2013" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(195, 88, 49)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 2013</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3000" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(175, 43, 30)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3000</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(165, 32, 25)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(162, 35, 29)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(155, 17, 30)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(117, 21, 30)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(94, 33, 41)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(53, 31, 33)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3009" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(100, 36, 36)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3009</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(120, 31, 25)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(193, 135, 107)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3013" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(161, 35, 18)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3013</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3014" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(211, 110, 112)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3014</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3015" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(234, 137, 154)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3015</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3016" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(179, 40, 33)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3016</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3017" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(230, 50, 68)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3017</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3018" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(213, 48, 50)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3018</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3020" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(204, 6, 5)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3020</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3022" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(217, 80, 48)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3022</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3024" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(248, 0, 0)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3024</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3026" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(254, 0, 0)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3026</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3027" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(197, 29, 52)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3027</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3028" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(203, 50, 52)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3028</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3031" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(179, 36, 40)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3031</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3032" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(114, 20, 34)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3032</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 3033" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(180, 76, 67)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 3033</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(109, 63, 91)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(146, 43, 62)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(222, 76, 138)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(110, 28, 52)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(108, 70, 117)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4006" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(160, 52, 114)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4006</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(74, 25, 44)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4008" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(146, 78, 125)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4008</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4009" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(164, 125, 144)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4009</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4010" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(215, 45, 109)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4010</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(134, 115, 161)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 4012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(108, 104, 129)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 4012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5000" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(42, 46, 75)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5000</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(31, 52, 56)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(32, 33, 79)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(29, 30, 51)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(24, 23, 28)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(30, 45, 110)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(62, 95, 138)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5008" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(38, 37, 45)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5008</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5009" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(2, 86, 105)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5009</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5010" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(14, 41, 75)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5010</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(35, 26, 36)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(59, 131, 189)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5013" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(30, 33, 61)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5013</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5014" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(96, 110, 140)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5014</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5015" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(34, 113, 179)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5015</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5017" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(6, 57, 113)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5017</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5018" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(63, 136, 143)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5018</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5019" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(27, 85, 131)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5019</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5020" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(29, 51, 74)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5020</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5021" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(37, 109, 123)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5021</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5022" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(37, 40, 80)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5022</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5023" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(73, 103, 141)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5023</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5024" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(93, 155, 155)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5024</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5025" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(42, 100, 120)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5025</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 5026" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(16, 44, 84)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 5026</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6000" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(49, 102, 80)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6000</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(40, 114, 51)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(45, 87, 44)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(66, 70, 50)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(31, 58, 61)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(47, 69, 56)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6006" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(62, 59, 50)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6006</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(52, 59, 41)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6008" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(57, 53, 42)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6008</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6009" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(49, 55, 43)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6009</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6010" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(53, 104, 45)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6010</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(88, 114, 70)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(52, 62, 64)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6013" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(108, 113, 86)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6013</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6014" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(71, 64, 46)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6014</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6015" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(59, 60, 54)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6015</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6016" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(30, 89, 69)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6016</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6017" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(76, 145, 65)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6017</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6018" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(87, 166, 57)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6018</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6019" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(189, 236, 182)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6019</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6020" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(46, 58, 35)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6020</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6021" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(137, 172, 118)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6021</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6022" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(37, 34, 27)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6022</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6024" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(48, 132, 70)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6024</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6025" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(61, 100, 45)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6025</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6026" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(1, 93, 82)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6026</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6027" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(132, 195, 190)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6027</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6028" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(44, 85, 69)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6028</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6029" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(32, 96, 61)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6029</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6032" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(49, 127, 67)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6032</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6033" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(73, 126, 118)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6033</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6034" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(127, 181, 181)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6034</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6035" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(28, 84, 45)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6035</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6036" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(25, 55, 55)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6036</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6037" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(0, 143, 57)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6037</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 6038" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(0, 187, 45)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 6038</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7000" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(120, 133, 139)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7000</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(138, 149, 151)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(126, 123, 82)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(108, 112, 89)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(150, 153, 146)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(100, 107, 99)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7006" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(109, 101, 82)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7006</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7008" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(106, 95, 49)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7008</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7009" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(77, 86, 69)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7009</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7010" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(76, 81, 74)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7010</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(67, 75, 77)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(78, 87, 84)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7013" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(70, 69, 49)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7013</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7015" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(67, 71, 80)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7015</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7016" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(41, 49, 51)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7016</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7021" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(35, 40, 43)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7021</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7022" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(51, 47, 44)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7022</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7023" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(104, 108, 94)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7023</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7024" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(71, 74, 81)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7024</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7026" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(47, 53, 59)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7026</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7030" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(139, 140, 122)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7030</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7031" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(71, 75, 78)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7031</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7032" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(184, 183, 153)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7032</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7033" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(125, 132, 113)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7033</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7034" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(143, 139, 102)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7034</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7035" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(215, 215, 215)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7035</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7036" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(127, 118, 121)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7036</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7037" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(125, 127, 125)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7037</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7038" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(195, 195, 195)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7038</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7039" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(108, 105, 96)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7039</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7040" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(157, 161, 170)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7040</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7042" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(141, 148, 141)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7042</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7043" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(78, 84, 82)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7043</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7044" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(202, 196, 176)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7044</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7045" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(144, 144, 144)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7045</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7046" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(130, 137, 143)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7046</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7047" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(208, 208, 208)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7047</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 7048" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(137, 129, 118)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 7048</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8000" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(130, 108, 52)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8000</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(149, 95, 32)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(108, 59, 42)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(115, 66, 34)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(142, 64, 42)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(89, 53, 31)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8008" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(111, 79, 40)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8008</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(91, 58, 41)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8012" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(89, 35, 33)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8012</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8014" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(56, 44, 30)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8014</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8015" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(99, 58, 52)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8015</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8016" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(76, 47, 39)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8016</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8017" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(69, 50, 46)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8017</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8019" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(64, 58, 58)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8019</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8022" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(33, 33, 33)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8022</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8023" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(166, 94, 46)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8023</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8024" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(121, 85, 61)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8024</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8025" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(117, 92, 72)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8025</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8028" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(78, 59, 49)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8028</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 8029" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(118, 60, 40)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 8029</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9001" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(250, 244, 227)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9001</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9002" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(231, 235, 218)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9002</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9003" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(244, 244, 244)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9003</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9004" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(40, 40, 40)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9004</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9005" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(10, 10, 10)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9005</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9006" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(165, 165, 165)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9006</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9007" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(143, 143, 143)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9007</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9010" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(255, 255, 255)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9010</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9011" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(28, 28, 28)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9011</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9016" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(246, 246, 246)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9016</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9017" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(30, 30, 29)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9017</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9018" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(215, 215, 215)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9018</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9022" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(156, 156, 156)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9022</p>
</div><div class="col-lg-1 col-md-2 col-sm-4 col-xs-3 chosed" name="ral 9023" style="text-align:center"><p data-bs-dismiss="modal" onclick="paleta('RAL',this.textContent)" style="cursor: pointer;"><img style="width: 100px;background-color: rgb(130, 130, 130)" class="img-responsive rounded-circle" src="<?php echo plugin_dir_url(__FILE__).'../imagenes/nuevosColores/plantillaColores.png'?>">RAL 9023</p>
</div>


</div>

<script type="text/javascript">


	var input = document.getElementById("myInputRAL");
input.addEventListener("input", myFunction);

function myFunction(e) {
  var filter = e.target.value.toUpperCase();

  var list = document.getElementById("listRAL");
  var divs = list.getElementsByTagName("div");
  for (var i = 0; i < divs.length; i++) {
    var a = divs[i].getElementsByTagName("a")[0];

    if (a) {
      if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
        divs[i].style.display = "";
      } else {
        divs[i].style.display = "none";
      }
    }
  }

}



</script>